# config/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']